# Generated by Django 5.0 on 2023-12-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
