# Generated by Django 5.0 on 2023-12-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos/'),
        ),
    ]
